<a href="https://colab.research.google.com/github/mohamedhossam23/Data-Prepration/blob/main/Decision_Tree_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [16]:
data = pd.read_csv("Social_Network_Ads.csv")
data.head()

Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [17]:
x = data.iloc[:, :-1].values
y = data.iloc[:, -1].values

In [18]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

In [19]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [20]:
x_train

array([[ 2.06471778, -0.78725145],
       [-0.17662777, -1.04867013],
       [-1.63837487, -0.03204194],
       [-1.15112584, -1.57150749],
       [ 2.16216758, -0.78725145],
       [-1.54092507, -1.22294925],
       [ 0.11572165, -0.29346062],
       [-0.566427  , -1.48436793],
       [-0.17662777,  1.42028404],
       [-1.24857565,  0.60698149],
       [ 1.86981816, -1.25199577],
       [-1.34602545, -0.4096467 ],
       [ 0.40807106, -0.46773974],
       [-0.46897719, -0.52583278],
       [ 0.8953201 , -1.28104229],
       [ 0.8953201 , -0.5548793 ],
       [-0.27407758, -0.72915842],
       [ 1.28511932,  1.88502836],
       [-1.54092507, -0.4096467 ],
       [ 1.48001894,  0.37460933],
       [-0.85877642, -1.19390273],
       [ 0.8953201 , -1.13580969],
       [ 0.01827184,  1.27505145],
       [ 0.21317145, -0.35155366],
       [-0.76132661,  1.362191  ],
       [ 0.21317145,  0.1712837 ],
       [-0.76132661,  0.28746977],
       [-1.63837487,  0.54888845],
       [-0.566427  ,

In [21]:
from sklearn.tree import DecisionTreeClassifier
Classifier = DecisionTreeClassifier(criterion="entropy", random_state=0)
Classifier.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [22]:
Classifier.predict(sc.transform([[30,87000]]))

array([0])

In [24]:
y_pred = Classifier.predict(x_test)
Ftest = np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1)
Ftest

array([[1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 1],
       [1, 1],
       [1, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [1, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1,

In [25]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
cm

array([[49,  6],
       [ 4, 21]])

In [26]:
acs = accuracy_score(y_test, y_pred)
acs

0.875